name = "flypigai-ca"
pages_build_output_dir = "out"
compatibility_date = "2026-07-23"

[[d1_databases]]
binding = "FLYPIG_DB"
database_name = "flypigai-events-dev"
database_id = "a93a9a4d-9cea-4c3f-a387-59ca97ac3594"

[[queues.producers]]
binding = "OUTBOUND_EVENTS"
queue = "flypigai-outbound-dev"

[env.preview]

[[env.preview.d1_databases]]
binding = "FLYPIG_DB"
database_name = "flypigai-events-dev"
database_id = "a93a9a4d-9cea-4c3f-a387-59ca97ac3594"

[[env.preview.queues.producers]]
binding = "OUTBOUND_EVENTS"
queue = "flypigai-outbound-dev"

[env.production]

[[env.production.d1_databases]]
binding = "FLYPIG_DB"
database_name = "flypigai-events-prod"
database_id = "f571464e-86e4-47d5-9651-0afaeb84613a"

[[env.production.queues.producers]]
binding = "OUTBOUND_EVENTS"
queue = "flypigai-outbound-prod"
