import type { Metadata } from "next";
import JsonLd from "../../components/JsonLd";
import { SiteFooter, SiteHeader } from "../../components/SiteChrome";
import { formattedAddress, siteIdentity } from "../../lib/site";
import { makeMetadata, siteUrl } from "../seo";

export const metadata: Metadata = makeMetadata({
  title: "About FlyPig AI",
  description: "About FlyPig AI, an independent Canada-Taiwan Edge AI and Physical AI intelligence initiative operated by ICareU Global Trading Ltd. in Delta, British Columbia.",
  path: "/about",
  enPath: "/about",
  zhPath: "/zh/about",
});

export default function AboutPage() {
  return <main>
    <JsonLd data={{ "@context": "https://schema.org", "@type": "AboutPage", "@id": `${siteUrl}/about#page`, name: "About FlyPig AI", url: `${siteUrl}/about`, mainEntity: { "@id": `${siteIdentity.founder.url}#person` }, isPartOf: { "@id": `${siteUrl}/#website` } }} />
    <JsonLd data={{ "@context": "https://schema.org", "@type": "Person", "@id": `${siteIdentity.founder.url}#person`, name: siteIdentity.founder.name, url: siteIdentity.founder.url, worksFor: { "@id": `${siteUrl}/#organization` }, knowsAbout: ["AI automation", "Digital products", "Canada-Taiwan business development"] }} />
    <SiteHeader languageHref="/zh/about" />
    <section className="hero shell about-hero"><p className="eyebrow">About FlyPig AI</p><h1>Independent intelligence between product need and technology capability.</h1><p className="lead">FlyPig AI is a Canadian, founder-led research and opportunity-development initiative focused on the intersection of Canadian product needs and Taiwan&apos;s Edge AI, semiconductor, embedded computing and Physical AI ecosystem.</p></section>
    <section className="section shell"><div className="section-head"><div><p className="eyebrow">What we are</p><h2>An intelligence layer, not an official industry body.</h2></div><p className="section-copy">FlyPig AI publishes source-based technology and ecosystem research, organizes product requirements, and may facilitate qualified conversations when there is a credible fit. Public coverage does not mean that FlyPig AI is an authorized distributor, supplier representative or official partner of a company discussed.</p></div><div className="grid3"><article className="card"><span className="num">01</span><h3>Founder-led</h3><p>Direct responsibility for research standards, market interpretation and qualified introductions.</p></article><article className="card"><span className="num">02</span><h3>Cross-market</h3><p>Canadian product and operator context connected to Taiwan technology and manufacturing intelligence.</p></article><article className="card"><span className="num">03</span><h3>Evidence-based</h3><p>Primary sources, visible disclosures and preserved uncertainty take priority over broad claims.</p></article></div></section>
    <section className="section shell"><div className="section-head"><div><p className="eyebrow">Working principles</p><h2>Practical, bounded and evidence-led.</h2></div><p className="section-copy">Robotics and Physical AI markets are full of impressive demonstrations. FlyPig AI evaluates whether a technology route can address real commercial conditions such as local support, deployment constraints, product maturity and measurable outcomes.</p></div><div className="grid3"><article className="card"><span className="num">Principle</span><h3>Start with fit</h3><p>Before outreach, clarify the use case, buyer profile, support expectations, product maturity and reasons Canada is a credible market.</p></article><article className="card"><span className="num">Principle</span><h3>Separate signal from hype</h3><p>Official sources, documented specifications and clearly stated deployment constraints carry more weight than broad claims about robotics adoption.</p></article><article className="card"><span className="num">Principle</span><h3>Respect the boundary</h3><p>FlyPig AI does not certify products, provide legal advice, approve site safety or claim to represent the full Canadian ecosystem.</p></article></div></section>
    <section className="section dark"><div className="shell"><div className="section-head"><div><p className="eyebrow">Public research initiative</p><h2>Canada Physical AI Atlas</h2></div><div><p className="section-copy">The Atlas is a market-research and ecosystem-mapping initiative developed by FlyPig AI. It organizes public information about companies, technologies, industries and regions. It is not an official government directory or a claim of endorsement.</p><div className="actions"><a className="pill primary" href="/atlas">Explore the Atlas</a><a className="pill secondary" href="/atlas/methodology">Read the methodology</a></div></div></div></div></section>
    <section className="section shell founder"><div><p className="eyebrow">Founder</p><h2>{siteIdentity.founder.name}</h2><p className="section-copy">M.K. Hsu works across AI automation, digital products and cross-border business development, with experience spanning Taiwan and Canada. He founded FlyPig AI to build a clearer evidence layer between Canadian product intent and Taiwan technology capability.</p><div className="actions"><a className="pill secondary" href={siteIdentity.founder.url} target="_blank" rel="noreferrer">Founder profile ↗</a><a className="pill secondary" href="/editorial-policy">Editorial policy</a></div></div><div className="founder-card"><span className="mono">Delta · British Columbia · Canada</span><h3>{siteIdentity.brandName}</h3><p>Independent Canada-Taiwan Edge AI and Physical AI intelligence.</p></div></section>
    <section className="section shell"><div className="section-head"><div><p className="eyebrow">Legal operator</p><h2>{siteIdentity.legalName}</h2></div><div><p className="section-copy">FlyPig AI is operated by {siteIdentity.legalName}.</p><p className="section-copy">{formattedAddress()}<br /><a href={`mailto:${siteIdentity.email}`}>{siteIdentity.email}</a></p></div></div></section>
    <SiteFooter />
  </main>;
}
