"use client";

import { FormEvent, useState } from "react";

type Locale = "en" | "zh";
const copy={en:{submit:"Send inquiry",sending:"Sending...",success:"Thank you. Your inquiry has been sent.",error:"We could not send your inquiry. Please try again or email info@flypigai.ca."},zh:{submit:"送出洽詢",sending:"傳送中...",success:"謝謝，您的洽詢已成功送出。",error:"目前無法送出，請稍後再試，或直接寄信至 info@flypigai.ca。"}};

export default function ContactForm({locale="en"}:{locale?:Locale}){
 const[status,setStatus]=useState<"idle"|"sending"|"success"|"error">("idle");
 async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();setStatus("sending");const form=event.currentTarget;const formData=new FormData(form);const data={...Object.fromEntries(formData.entries()),support:formData.getAll("support")};try{const response=await fetch("/api/contact",{method:"POST",headers:{"Content-Type":"application/json","Idempotency-Key":crypto.randomUUID()},body:JSON.stringify({...data,locale})});if(!response.ok)throw new Error("Request failed");form.reset();setStatus("success")}catch{setStatus("error")}}
 const zh=locale==="zh";
 return <form className="contact-form" onSubmit={submit}>
  <div className="form-grid two">
   <label>{zh?"姓名":"Name"}<input name="name" required maxLength={100}/></label><label>{zh?"公司／機構":"Company / organization"}<input name="company" required maxLength={160}/></label><label>{zh?"Email":"Work email"}<input name="email" type="email" required maxLength={160}/></label><label>{zh?"電話／WhatsApp（選填）":"Phone / WhatsApp (optional)"}<input name="phone" maxLength={60}/></label><label>{zh?"國家／地區":"Country / region"}<input name="country" required maxLength={100}/></label><label>{zh?"公司網站":"Company website"}<input name="website" type="url" placeholder="https://" maxLength={240}/></label>
  </div>
  <label>{zh?"您屬於哪一類型？":"Which best describes your organization?"}<select name="audience" required defaultValue=""><option value="" disabled>{zh?"請選擇":"Select one"}</option><option value="canadian-product-team">{zh?"加拿大產品、工程或採購團隊":"Canadian product, engineering or procurement team"}</option><option value="taiwan-technology-company">{zh?"台灣技術、零組件或系統業者":"Taiwan technology, component or system company"}</option><option value="research-investment">{zh?"研究機構、投資人或產業組織":"Research, investment or industry organization"}</option><option value="other">{zh?"其他":"Other"}</option></select></label>
  <div className="form-grid two">
   <label>{zh?"主要產品／技術領域":"Primary product / technology area"}<select name="technology" required defaultValue=""><option value="" disabled>{zh?"請選擇":"Select one"}</option><option value="components">{zh?"關鍵零組件與子系統":"Critical components and subsystems"}</option><option value="drones">{zh?"無人機與任務酬載":"Drones and mission payloads"}</option><option value="mobile-robots">{zh?"AMR、UGV、四足或人形機器人":"AMR, UGV, quadruped or humanoid robots"}</option><option value="sensors-ai">{zh?"感測器、邊緣 AI、導航與機器視覺":"Sensors, edge AI, navigation and machine vision"}</option><option value="services">{zh?"系統整合、軟體或產業服務":"Integration, software or industry services"}</option><option value="other">{zh?"其他":"Other"}</option></select></label>
   <label>{zh?"目前合作階段":"Current stage"}<select name="stage" required defaultValue=""><option value="" disabled>{zh?"請選擇":"Select one"}</option><option value="requirements">{zh?"正在釐清產品需求與限制":"Clarifying product requirements and constraints"}</option><option value="technology-route">{zh?"正在比較技術路徑或候選方案":"Comparing technology routes or candidates"}</option><option value="canada-readiness">{zh?"正在評估加拿大應用與 Design-In 準備度":"Assessing Canada application and design-in readiness"}</option><option value="qualified-introduction">{zh?"已有明確匹配問題，評估技術引介":"Evaluating a qualified technical introduction"}</option><option value="editorial">{zh?"公開資料更正或編輯詢問":"Public-data correction or editorial inquiry"}</option></select></label>
  </div>
  <fieldset><legend>{zh?"您希望獲得哪些協助？（可複選）":"What support are you looking for? (Select all that apply)"}</legend><div className="check-grid">{[["requirement-brief",zh?"產品需求與限制整理":"Product requirement and constraint brief"],["architecture-options",zh?"架構選項與技術路徑比較":"Architecture options and technology-route comparison"],["candidate-qualification",zh?"台灣技術候選與資格評估":"Taiwan technology candidate qualification"],["canada-application-fit",zh?"加拿大應用適配與 Design-In 準備度":"Canada application fit and design-in readiness"],["evidence-gap-review",zh?"產品證據缺口與整合摩擦檢視":"Evidence-gap and integration-friction review"],["bounded-introduction",zh?"有邊界的技術引介評估":"Bounded technical-introduction assessment"]].map(([value,label])=><label className="check" key={value}><input type="checkbox" name="support" value={value}/>{label}</label>)}</div></fieldset>
  <label>{zh?"請簡述產品、需求與希望達成的目標":"Tell us about your product, requirements and desired outcome"}<textarea name="message" required minLength={20} maxLength={3000} rows={8}/></label>
  <div className="form-grid two"><label>{zh?"預計時程":"Expected timeline"}<input name="timeline" placeholder={zh?"例如：3–6 個月":"e.g. 3–6 months"} maxLength={100}/></label><label>{zh?"如何得知 FlyPig AI？":"How did you hear about FlyPig AI?"}<input name="referral" maxLength={160}/></label></div>
  <label className="honeypot" aria-hidden="true">Website<input name="company_site" tabIndex={-1} autoComplete="off"/></label>
  <div className="form-submit"><button className="pill primary" type="submit" disabled={status==="sending"}>{status==="sending"?copy[locale].sending:copy[locale].submit}</button>{status==="success"&&<p className="form-message success">{copy[locale].success}</p>}{status==="error"&&<p className="form-message error">{copy[locale].error}</p>}</div>
 </form>
}
